// Code generated by mockery v2.10.0. DO NOT EDIT.

package user

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockApiRestController is an autogenerated mock type for the ApiRestController type
type MockApiRestController struct {
	mock.Mock
}

// CreateObject provides a mock function with given fields: _a0, _a1
func (_m *MockApiRestController) CreateObject(_a0 context.Context, _a1 string) (int, error) {
	ret := _m.Called(_a0, _a1)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
